name: Deploy to Cloud Run
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE: "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_REPOSITORY }}/${{ secrets.GCP_SERVICE }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet
      - name: Build Docker image
        run: docker build -t "$IMAGE:latest" -f my-node-app/Dockerfile my-node-app
      - name: Push Docker image
        run: docker push "$IMAGE:latest"
      - name: Deploy to Cloud Run
        run: gcloud run deploy "${{ secrets.GCP_SERVICE }}" \
               --image="$IMAGE:latest" \
               --region="${{ secrets.GCP_REGION }}" \
               --platform=managed \
               --allow-unauthenticated




